---
title: "sr thesis components"
author: "Zoe Fung"
date: "8/31/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load required packages
library(readr)
library(ggplot2)
library(tibble)
library(janitor)
library(plyr)
library(dplyr)
library(stringr)
library(tidyr)
library(forcats)
library(ggthemes)
```

## data cleaning 

### fire severity data

#### fire locations
```{r}
# load USDA 1 dataset
USDAfires <- read.csv("data/USDA_RDA_fires_list.csv") %>%
  clean_names() %>% # standardize dataset variable names
  filter(state=="California") # subset dataset to inlcude only CA fires
# create list of fires in CA from USDA 1 dataset
CAfires <- distinct(USDAfires,yr_fire_name)

# load USDA 1 fire severity dataset
USDAseverity <- read.csv("data/USDA_RDA_pre_post_trees.csv") %>%
  clean_names() %>% # standardize dataset variable names
  filter(yr_fire_name==c(CAfires$yr_fire_name)) # subset dataset to include only CA fires

# create list of fires in CA that have species & fire severity data
CAfires_clean <- distinct(USDAseverity,yr_fire_name)

# filter USDA fires dataset to only include CA fires w/ location, species, & fire severity data
USDAfires_clean <- USDAfires %>%
  filter(yr_fire_name %in% CAfires_clean$yr_fire_name) 

# create a .csv file for USDAfires_clean
write.csv(USDAfires_clean, "USDAfires_clean.csv") # how do i specify a path for this file to be created in the data folder?

# create vectors for lat, long, and fire year/name
latitude <- c(37.279, 37.857, 38.805437, 36.874, 37.279722)
longitude <- c(-119.318, -120.086, -120.629714, -118.905, -119.50014)
yr_fire_name <- c("2013 - Aspen", "2013 - Rim", "2014 - King", "2015 - Rough", "2015 - Willow")

# create dataframe 
USDA2fires_clean <- as.data.frame(cbind(yr_fire_name,latitude,longitude))

# create a .csv file for USDA2fires_clean
write.csv(USDA2fires_clean, "USDA2fires_clean.csv")

### PLOT locations for Nicole's data -- Laguna Mtn, Bluff Mesa, & Thomas fires
# read in all plot location data & organize
laguna_location <- read_csv("data/Nicole-data/LagunaMtn_plot_coordinates.csv") %>%
  clean_names() %>% # standardize column names
  select(site_year, plot_id, treatment_unit, easting, northing) %>% # subset data 
  as.data.frame() %>%
  drop_na("plot_id")
bluffmesa_location <- read_csv("data/Nicole-data/BluffMesa_plot_coordinates.csv") %>%
  clean_names() %>% # standardize column names
  select(site_year, plot_id, treatment_unit, easting, northing) %>% # subset data
  as.data.frame() %>%
  drop_na("plot_id")
thomas_location <- read_csv("data/Nicole-data/ThomasFire_plot_coordinates.csv") %>%
  clean_names() %>% # standardize column names
  select(site_year, plot_id, treatment_unit, easting, northing) %>% # subset data 
  as.data.frame() %>%
  drop_na("plot_id")
```

#### pre-fire: USDA/USFS data
```{r}
# load USDA 1 pre & post fire data
USDA1_prefire <- read.csv("data/USDA_RDA_pre_post_trees.csv") %>%
  clean_names() %>% # standardize column names
  filter(yr_fire_name %in% USDAfires_clean$yr_fire_name) %>%
  select(yr_fire_name, species, dataset, tree_num, genus, species_name, dbh_cm, drc_cm, ht_m, hcb_pre, cr_pre, cc, vr, cl_m) # subset data to only include CA fires w/ location, species, and fire severity data

# add latitude data
USDA1_prefire <- mutate(USDA1_prefire, latitude=case_when(
    str_detect(yr_fire_name, "1989 - SEKI Crystal") ~ "36.60068",
    str_detect(yr_fire_name, "SEKI Grant West I") ~ "36.74582",
    str_detect(yr_fire_name, "SEKI Highway 2") ~ "36.57336",
    str_detect(yr_fire_name, "SEKI Tharps") ~ "36.56328",
    str_detect(yr_fire_name, "SEKI Deer Creek PNF") ~ "36.57336",
    str_detect(yr_fire_name, "SEKI Grant West") ~ "36.74582",
    str_detect(yr_fire_name, "LAVO Knob/ Lost Creek") ~ "40.56738",
    str_detect(yr_fire_name, "SEKI Hole-inthe-Wall") ~ "36.78695",
    str_detect(yr_fire_name, "SEKI Picnic Estates") ~ "36.79198",
    str_detect(yr_fire_name, "Crystal") ~ "39.51724",
    str_detect(yr_fire_name, "LAVO Butte Lake") ~ "40.58129",
    str_detect(yr_fire_name, "SEKI Mineral King") ~ "36.46600",
    str_detect(yr_fire_name, "WHIS Brandy Creek") ~ "40.61878",
    str_detect(yr_fire_name, "1996 - WHIS Shasta Divide") ~ "40.57916",
    str_detect(yr_fire_name, "REDW Mainstem") ~ "41.12729",
    str_detect(yr_fire_name, "REDW Midbasin") ~ "41.13717",
    str_detect(yr_fire_name, "Bucks") ~ "39.88539",
    str_detect(yr_fire_name, "SEKI Hercules") ~ "36.56936",
    str_detect(yr_fire_name, "SEKI Mineral KingS10") ~ "36.46601",
    str_detect(yr_fire_name, "Storrie") ~ "40.02744",
    str_detect(yr_fire_name, "Volcano Spring") ~ "39.15980",
    str_detect(yr_fire_name, "FSS2") ~ "36.59506",
    str_detect(yr_fire_name, "FSS5") ~ "36.58481",
    str_detect(yr_fire_name, "FSS6") ~ "36.58518",
    str_detect(yr_fire_name, "Southern Cascades Goosenest CA 174") ~ "41.54627",
    str_detect(yr_fire_name, "Southern Cascades Goosenest CA 178") ~ "41.56750",
    str_detect(yr_fire_name, "Southern Cascades Goosenest CA 179") ~ "41.58725",
    str_detect(yr_fire_name, "Southern Sierra Nevada Sequoia CA 1") ~ "36.59455",
    str_detect(yr_fire_name, "Southern Sierra Nevada Sequoia CA 4") ~ "36.58567",
    str_detect(yr_fire_name, "Southern Sierra Nevada Sequoia CA 5") ~ "36.58582",
    str_detect(yr_fire_name, "Star") ~ "39.09857",
    str_detect(yr_fire_name, "Swain") ~ "40.67535",
    str_detect(yr_fire_name, "Blodgett 129 - 60") ~ "38.91730",
    str_detect(yr_fire_name, "Blodgett 130 - 340") ~ "38.89821",
    str_detect(yr_fire_name, "Blodgett 131 - 400") ~ "38.89666",
    str_detect(yr_fire_name, "Cone") ~ "40.75172",
    str_detect(yr_fire_name, "McNalley") ~ "36.57336",
    str_detect(yr_fire_name, "REDW Copper Creek") ~ "41.15085",
    str_detect(yr_fire_name, "Southern Cascades Goosenest CA 181") ~ "41.60037",
    str_detect(yr_fire_name, "Southern Cascades Goosenest CA 182") ~ "41.56346",
    str_detect(yr_fire_name, "Southern Cascades Goosenest CA 183") ~ "41.55452",
    str_detect(yr_fire_name, "Southern Sierra Nevada Sequoia CA 2") ~ "36.59416",
    str_detect(yr_fire_name, "Southern Sierra Nevada Sequoia CA 3") ~ "36.59189",
    str_detect(yr_fire_name, "Southern Sierra Nevada Sequoia CA 8") ~ "36.57340",
    str_detect(yr_fire_name, "LABE South Boundary") ~ "41.69815",
    str_detect(yr_fire_name, "2003 - WHIS Shasta Divide") ~ "40.57916",
    str_detect(yr_fire_name, "Power") ~ "38.50190",
    str_detect(yr_fire_name, "Tennant") ~ "41.55805",
    str_detect(yr_fire_name, "Tharps2") ~ "36.56328",
    str_detect(yr_fire_name, "Harding") ~ "39.63345",
    str_detect(yr_fire_name, "SEKI Lewis Creek") ~ "36.76013",
    str_detect(yr_fire_name, "Angora") ~ "38.88529",
    str_detect(yr_fire_name, "Antelope") ~ "40.14120",
    str_detect(yr_fire_name, "Grass Valley") ~ "34.26739",
    str_detect(yr_fire_name, "PW-4") ~ "37.80125",
    str_detect(yr_fire_name, "American River Complex") ~ "39.22988",
    str_detect(yr_fire_name, "Peterson") ~ "40.89497",
    str_detect(yr_fire_name, "Piute") ~ "35.48923",
    str_detect(yr_fire_name, "Rich") ~ "40.06137",
    str_detect(yr_fire_name, "2008 - Seki Crystal") ~ "36.60068",
    str_detect(yr_fire_name, "WHIS White Rock") ~ "40.64606",
    str_detect(yr_fire_name, "Milford") ~ "40.10646",
    str_detect(yr_fire_name, "REDW Eastside") ~ "41.14705",
    str_detect(yr_fire_name, "Mountain") ~ "33.71030",
    str_detect(yr_fire_name, "Rim") ~ "37.90192",
    str_detect(yr_fire_name, "Salmon Complex") ~ "41.31864",
    str_detect(yr_fire_name, "Wooded Hills") ~ "32.85336"
  ))

# add longitude data
USDA1_prefire <- mutate(USDA1_prefire, longitude=case_when(
    str_detect(yr_fire_name, "1989 - SEKI Crystal") ~ "-118.8102",
    str_detect(yr_fire_name, "SEKI Grant West I") ~ "-118.9772",
    str_detect(yr_fire_name, "SEKI Highway 2") ~ "-118.7604",
    str_detect(yr_fire_name, "SEKI Tharps") ~ "-118.7428",
    str_detect(yr_fire_name, "SEKI Deer Creek PNF") ~ "-118.6585", 
    str_detect(yr_fire_name, "SEKI Grant West") ~ "-118.9772",
    str_detect(yr_fire_name, "LAVO Knob/ Lost Creek") ~ "-121.5252",
    str_detect(yr_fire_name, "SEKI Hole-inthe-Wall") ~ "-118.6302",
    str_detect(yr_fire_name, "SEKI Picnic Estates") ~ "-118.6669",
    str_detect(yr_fire_name, "Crystal") ~ "-120.0372",
    str_detect(yr_fire_name, "LAVO Butte Lake") ~ "-121.2966",
    str_detect(yr_fire_name, "SEKI Mineral King") ~ "-118.6934",
    str_detect(yr_fire_name, "WHIS Brandy Creek") ~ "-122.5739",
    str_detect(yr_fire_name, "1996 - WHIS Shasta Divide") ~ "-122.5247",
    str_detect(yr_fire_name, "REDW Mainstem") ~ "-123.8691",
    str_detect(yr_fire_name, "REDW Midbasin") ~ "-123.8881",
    str_detect(yr_fire_name, "Bucks") ~ "-121.3127",
    str_detect(yr_fire_name, "SEKI Hercules") ~ "-118.7515",
    str_detect(yr_fire_name, "SEKI Mineral KingS10") ~ "-118.6935",
    str_detect(yr_fire_name, "Storrie") ~ "-121.2872",
    str_detect(yr_fire_name, "Volcano Spring") ~ "-120.6647",
    str_detect(yr_fire_name, "FSS2") ~ "-118.7470",
    str_detect(yr_fire_name, "FSS5") ~ "-118.7552",
    str_detect(yr_fire_name, "FSS6") ~ "-118.7596",
    str_detect(yr_fire_name, "Southern Cascades Goosenest CA 174") ~ "-121.8868",
    str_detect(yr_fire_name, "Southern Cascades Goosenest CA 178") ~ "-121.8468",
    str_detect(yr_fire_name, "Southern Cascades Goosenest CA 179") ~ "-121.8417",
    str_detect(yr_fire_name, "Southern Sierra Nevada Sequoia CA 1") ~ "-118.7470",
    str_detect(yr_fire_name, "Southern Sierra Nevada Sequoia CA 4") ~ "-118.7549",
    str_detect(yr_fire_name, "Southern Sierra Nevada Sequoia CA 5") ~ "-118.7592",
    str_detect(yr_fire_name, "Star") ~ "-120.4895",
    str_detect(yr_fire_name, "Swain") ~ "-121.2609",
    str_detect(yr_fire_name, "Blodgett 129 - 60") ~ "-120.6639",
    str_detect(yr_fire_name, "Blodgett 130 - 340") ~ "-120.6545",
    str_detect(yr_fire_name, "Blodgett 131 - 400") ~ "-120.6489",
    str_detect(yr_fire_name, "Cone") ~ "-121.1582",
    str_detect(yr_fire_name, "McNalley") ~ "-118.4001",
    str_detect(yr_fire_name, "REDW Copper Creek") ~ "-123.8945",
    str_detect(yr_fire_name, "Southern Cascades Goosenest CA 181") ~ "-121.8468",
    str_detect(yr_fire_name, "Southern Cascades Goosenest CA 182") ~ "-121.8937",
    str_detect(yr_fire_name, "Southern Cascades Goosenest CA 183") ~ "-121.8638",
    str_detect(yr_fire_name, "Southern Sierra Nevada Sequoia CA 2") ~ "-118.7520",
    str_detect(yr_fire_name, "Southern Sierra Nevada Sequoia CA 3") ~ "-118.7552",
    str_detect(yr_fire_name, "Southern Sierra Nevada Sequoia CA 8") ~ "-118.7721",
    str_detect(yr_fire_name, "LABE South Boundary") ~ "-121.5030",
    str_detect(yr_fire_name, "2003 - WHIS Shasta Divide") ~ "-122.5247",
    str_detect(yr_fire_name, "Power") ~ "-120.2801",
    str_detect(yr_fire_name, "Tennant") ~ "-121.9136",
    str_detect(yr_fire_name, "Tharps2") ~ "-118.7428",
    str_detect(yr_fire_name, "Harding") ~ "-120.3098",
    str_detect(yr_fire_name, "SEKI Lewis Creek") ~ "-118.7051",
    str_detect(yr_fire_name, "Angora") ~ "-120.0365",
    str_detect(yr_fire_name, "Antelope") ~ "-120.5751",
    str_detect(yr_fire_name, "Grass Valley") ~ "-117.2301",
    str_detect(yr_fire_name, "PW-4") ~ "-119.8694",
    str_detect(yr_fire_name, "American River Complex") ~ "-120.6351",
    str_detect(yr_fire_name, "Peterson") ~ "-121.3170",
    str_detect(yr_fire_name, "Piute") ~ "-118.3568",
    str_detect(yr_fire_name, "Rich") ~ "-121.1244",
    str_detect(yr_fire_name, "2008 - Seki Crystal") ~ "-118.8102",
    str_detect(yr_fire_name, "WHIS White Rock") ~ "-122.5381",
    str_detect(yr_fire_name, "Milford") ~ "-120.3957",
    str_detect(yr_fire_name, "REDW Eastside") ~ "-123.8678",
    str_detect(yr_fire_name, "Mountain") ~ "--116.7062",
    str_detect(yr_fire_name, "Rim") ~ "--120.0836",
    str_detect(yr_fire_name, "Salmon Complex") ~ "-123.1824",
    str_detect(yr_fire_name, "Wooded Hills") ~ "-116.4381"
  ))

# determine how many data points are available for pre-fire data (include dbh measurements)
USDA1_prefire <- drop_na(USDA1_prefire, dbh_cm) %>% # 23,509 DBH data points
  distinct(yr_fire_name, species, dataset, tree_num, genus, species_name, dbh_cm, drc_cm, ht_m, hcb_pre, cr_pre, cc, vr, cl_m) # drop duplicate rows

# identify the species for which pre/post-fire data exists
USDA1_species <- distinct(USDA1_prefire, species)

# create list of the CA fires w/ pre-fire data available
USDA1pre_fires_list <- distinct(USDA1_prefire,yr_fire_name)

# create a dataset with only fire name, latitude, and longitude for pre-fire data
USDA1prefire_clean <- USDA1_prefire[, c("yr_fire_name", "latitude", "longitude")]

# remove repeat rows: keep only 1 row for each set of fire/coordinates
USDA1prefire_clean <- distinct(USDA1prefire_clean)

# write csv for USDA1 prefire data
write.csv(USDA1prefire_clean, "USDA1prefire_clean.csv")

# test mutate on a smaller data table
prefiretest <- slice(USDA1_prefire, 1:5) %>% # select first 5 rows of USDA1 prefire
  select(yr_fire_name, species, dataset) %>% # only keep first 3 variables
  mutate(latitude=case_when(
    str_detect(yr_fire_name, "Grass Valley") ~ "34.26739",
    str_detect(yr_fire_name, "FSS2") ~ "36.59506",
    str_detect(yr_fire_name, "FSS5") ~ "36.58481",
    str_detect(yr_fire_name, "McNalley") ~ "36.57336")) # add latitude column

# create data frame for USDA 1 post-fire data
USDA1_postfire <- read.csv("data/USDA_RDA_pre_post_trees.csv") %>%
  clean_names() %>% # standardize variable names
  filter(yr_fire_name %in% USDAfires_clean$yr_fire_name) %>%
  select(yr_fire_name, species, dataset, times_burned, tree_num, genus, species_name, csh_m, cls_m, clk_m, cls_percent, clk_percent, cvs_percent, cvk_percent, cbs, bcha_m, bchm_m, bch_percent, bca, ckr, gca, gir_percent) # select only columns relating to post-fire measurements

# determine how many data points are available for post-fire data (include crown scorch height & max bole char height measurements)
USDA1_postfire <- drop_na(USDA1_postfire, csh_m) %>% 
  drop_na(bchm_m) %>% 
  distinct(yr_fire_name, species, dataset, tree_num, genus, species_name, csh_m, cls_m, clk_m, cls_percent, clk_percent, cvs_percent, cvk_percent, cbs, bcha_m, bchm_m, bch_percent, bca, ckr, gca, gir_percent) # drop duplicate rows -- 6,970 data points w/ both crown scorch height and max bole char height

# load USDA 2 pre & post fire data
crag <- read.csv("data/USDA:USFS/2005_Crag/!FBAT_Trees_Crag_Rawdata")
```

#### pre-fire - Nicole's data 
```{r}
# load in all pre-fire data & organize
laguna_pre <- read_csv("data/Nicole/LagunaMtn_pre_2016.csv") %>%
  clean_names() %>% # standardize column names
  select(project, date, id, treatment, tag_number, status, species, dbh_cm, height_m, heigt_to_crown_m, dbh_ft, basal_area_sq_ft_indiv) %>% # subset data 
  as.data.frame() %>%
  rename("height_to_crown_m"="heigt_to_crown_m", "plot_id"="id", "treatment_unit"="treatment")
laguna_pre <- laguna_pre %>%
  mutate(tree_area = ((pi*(laguna_pre$dbh_cm^2)/4)/100)) # add column w/ area measurements for each tree

# load in raw pre-fire laguna mountain data (2020)

# setwd("data/Nicole/laguna/lagunamtnpre") 
# laguna_pre <- ldply(list.files(), read.csv, header=TRUE) # doesn't work

lm_128 <- read.csv("data/Nicole/laguna/lagunamtnpre/LM_128_2020_trees.csv") %>%
  mutate(plot_id = rep(128, length = 8))
lm_129 <- read.csv("data/Nicole/laguna/lagunamtnpre/LM_129_2020_trees.csv") %>%
  mutate(plot_id = rep(129, length = 12))
lm_130 <- read.csv("data/Nicole/laguna/lagunamtnpre/LM_130_2020_trees.csv") %>%
  mutate(plot_id = rep(130, length = 12))
lm_131 <- read.csv("data/Nicole/laguna/lagunamtnpre/LM_131_2020_trees.csv") %>%
  mutate(plot_id = rep(131, length = 7))
lm_132 <- read.csv("data/Nicole/laguna/lagunamtnpre/LM_132_2020_trees.csv") %>%
  mutate(plot_id = rep(132, length = 3))
lm_133 <- read.csv("data/Nicole/laguna/lagunamtnpre/LM_133_2020_trees.csv") %>%
  mutate(plot_id = rep(133, length = 6))
lm_134 <- read.csv("data/Nicole/laguna/lagunamtnpre/LM_134_2020_trees.csv") %>%
  mutate(plot_id = rep(134, length = 10))
lm_135 <- read.csv("data/Nicole/laguna/lagunamtnpre/LM_135_2020_trees.csv") %>%
  mutate(plot_id = rep(135, length = 6))
lm_137 <- read.csv("data/Nicole/laguna/lagunamtnpre/LM_137_2020_trees.csv") %>%
  mutate(plot_id = rep(137, length = 7))
lm_138 <- read.csv("data/Nicole/laguna/lagunamtnpre/LM_138_2020_trees.csv") %>%
  mutate(plot_id = rep(138, length = 7))
lm_139 <- read.csv("data/Nicole/laguna/lagunamtnpre/LM_139_2020_trees.csv") %>%
  mutate(plot_id = rep(139, length = 6))
lm_140 <- read.csv("data/Nicole/laguna/lagunamtnpre/LM_140_2020_trees.csv") %>%
  mutate(plot_id = rep(140, length = 7))
lm_141 <- read.csv("data/Nicole/laguna/lagunamtnpre/LM_141_2020_trees.csv") %>%
  mutate(plot_id = rep(141, length = 8))
lm_142 <- read.csv("data/Nicole/laguna/lagunamtnpre/LM_142_2020_trees.csv") %>%
  mutate(plot_id = rep(142, length = 8))
lm_143 <- read.csv("data/Nicole/laguna/lagunamtnpre/LM_143_2020_trees.csv") %>%
  mutate(plot_id = rep(143, length = 10))
lm_144 <- read.csv("data/Nicole/laguna/lagunamtnpre/LM_144_2020_trees.csv") %>%
  mutate(plot_id = rep(144, length = 6))
lm_170 <- read.csv("data/Nicole/laguna/lagunamtnpre/LM_170_2021_trees.csv") %>%
  mutate(plot_id = rep(170, length = 7))
lm_171 <- read.csv("data/Nicole/laguna/lagunamtnpre/LM_171_2021_trees.csv") %>%
  mutate(plot_id = rep(171, length = 8))
lm_172 <- read.csv("data/Nicole/laguna/lagunamtnpre/LM_172_2020_trees.csv") %>%
  mutate(plot_id = rep(172, length = 9))
lm_173 <- read.csv("data/Nicole/laguna/lagunamtnpre/LM_173_2021_trees.csv") %>%
  mutate(plot_id = rep(173, length = 15))
lm_175 <- read.csv("data/Nicole/laguna/lagunamtnpre/LM_175_2021_trees.csv") %>%
  mutate(plot_id = rep(175, length = 8))
lm_176 <- read.csv("data/Nicole/laguna/lagunamtnpre/LM_176_2021_trees.csv") %>%
  mutate(plot_id = rep(176, length = 7))
lm_177 <- read.csv("data/Nicole/laguna/lagunamtnpre/LM_177_2021_trees.csv") %>%
  mutate(plot_id = rep(177, length = 7))
lm_179 <- read.csv("data/Nicole/laguna/lagunamtnpre/LM_179_2021_trees.csv") %>%
  mutate(plot_id = rep(179, length = 6))
lm_180 <- read.csv("data/Nicole/laguna/lagunamtnpre/LM_180_2021_trees.csv") %>%
  mutate(plot_id = rep(180, length = 17))
lm_181 <- read.csv("data/Nicole/laguna/lagunamtnpre/LM_181_2021_trees.csv") %>%
  mutate(plot_id = rep(181, length = 19))
lm_195 <- read.csv("data/Nicole/laguna/lagunamtnpre/LM_195_2021_trees.csv") %>%
  mutate(plot_id = rep(195, length = 25))
lm_196 <- read.csv("data/Nicole/laguna/lagunamtnpre/LM_196_2021_trees.csv") %>%
  mutate(plot_id = rep(196, length = 8))
lm_197 <- read.csv("data/Nicole/laguna/lagunamtnpre/LM_197_2021_trees.csv") %>%
  mutate(plot_id = rep(197, length = 5))
lm_198 <- read.csv("data/Nicole/laguna/lagunamtnpre/LM_198_2021_trees.csv") %>%
  mutate(plot_id = rep(198, length = 7))
lm_199 <- read.csv("data/Nicole/laguna/lagunamtnpre/LM_199_2021_trees.csv") %>%
  mutate(plot_id = rep(199, length = 12))
lm_200 <- read.csv("data/Nicole/laguna/lagunamtnpre/LM_200_2021_trees.csv") %>%
  mutate(plot_id = rep(200, length = 11))

# combine raw pre-fire laguna data into one data frame
laguna_pre <- rbind(
  lm_128, lm_129, lm_130, lm_131, lm_132, lm_133, lm_134, lm_135, lm_137, lm_138, lm_139, lm_140, lm_141, lm_142, lm_143, lm_144, lm_170, lm_171, lm_172, lm_173, lm_175, lm_176, lm_177, lm_179, lm_180, lm_181, lm_195, lm_196, lm_197, lm_198, lm_199, lm_200) %>%
  clean_names() %>%
  select(plot_id, species, tag_no, status, dbh, ht, crwn_rto, crwn_rad, char_ht, scorch_ht, cr_sc_pct, uv1, uv2, uv3) %>%
  mutate(location = rep("Laguna", rep = 294))


# load in raw pre-fire bluff mesa data (2020)
bm_24_2020_trees <- read.csv("data/Nicole/bluffmesa/BM_24_2020_trees.csv") %>%
  mutate(plot_id = rep(24, length = 8))
bm_25_2020_trees <- read.csv("data/Nicole/bluffmesa/BM_25_2020_trees.csv") %>%
   mutate(plot_id = rep(25, length = 4))
bm_26_2020_trees <- read.csv("data/Nicole/bluffmesa/BM_26_2020_trees.csv") %>%
   mutate(plot_id = rep(26, length = 3))
bm_27_2020_trees <- read.csv("data/Nicole/bluffmesa/BM_27_2020_trees.csv") %>%
   mutate(plot_id = rep(27, length = 3))
bm_33_2020_trees <- read.csv("data/Nicole/bluffmesa/BM_33_2020_trees.csv") %>%
   mutate(plot_id = rep(33, length = 4))
bm_48_2020_trees <- read.csv("data/Nicole/bluffmesa/BM_48_2020_trees.csv") %>%
   mutate(plot_id = rep(48, length = 6))
bm_49_2020_trees <- read.csv("data/Nicole/bluffmesa/BM_49_2020_trees.csv") %>%
   mutate(plot_id = rep(49, length = 10))
bm_50_2020_trees <- read.csv("data/Nicole/bluffmesa/BM_50_2020_trees.csv") %>% 
   mutate(plot_id = rep(50, length = 4))
bm_51_2020_trees <- read.csv("data/Nicole/bluffmesa/BM_51_2020_trees.csv") %>%
   mutate(plot_id = rep(51, length = 4))
bm_52_2020_trees <- read.csv("data/Nicole/bluffmesa/BM_52_2020_trees.csv") %>%
   mutate(plot_id = rep(52, length = 3))
bm_53_2020_trees <- read.csv("data/Nicole/bluffmesa/BM_53_2020_trees.csv") %>%
   mutate(plot_id = rep(53, length = 5))

# combine raw pre-fire bluff mesa data into one data frame
bluffmesa_pre <- rbind(
  bm_24_2020_trees, bm_25_2020_trees, bm_26_2020_trees, bm_27_2020_trees, bm_33_2020_trees, bm_48_2020_trees, bm_49_2020_trees, bm_50_2020_trees, bm_51_2020_trees, bm_52_2020_trees, bm_53_2020_trees) %>%
  clean_names() %>%
  select(plot_id, species, tag_no, status, dbh, ht, crwn_rto, crwn_rad, char_ht, scorch_ht, cr_sc_pct, uv1, uv2, uv3) %>%
  mutate(location = rep("Bluff Mesa", length = 54))

prefire_whole <- rbind(
  laguna_pre, bluffmesa_pre
)
```

#### coordinate data
```{r}
# laguna mtn coordinates
LM_coord <- read.csv("data/Nicole/laguna/LM_coordinates.csv") %>%
  clean_names() %>%
  select(site_year, plot_id, easting, northing) %>%
  filter(plot_id > 127) %>%
  filter(!duplicated(plot_id))

# bluff mesa coordinates
BM_coord <- read.csv("data/Nicole/bluffmesa/BM_coordinates.csv") %>%
  clean_names() %>%
  select(site_year, plot_id, easting, northing) %>%
  filter(plot_id > 23) %>%
  filter(plot_id < 54) %>%
  slice(-(1:3)) %>%
  filter(!duplicated(plot_id))
```
```{r}
# calculation for tree area measurement
laguna_pre <- laguna_pre %>%
  mutate(tree_area = ((pi*(laguna_pre$dbh^2)/4)/100))
bluffmesa_pre <- bluffmesa_pre %>%
  mutate(tree_area = ((pi*(bluffmesa_pre$dbh^2)/4)/100)) # add column with area measurements for each tree (cm^2)

# since location data is organized by PLOT, find tree area per plot (subset by species)
laguna_species <- unique(laguna_pre$species) # create list of all species present in laguna fire data

laguna_pre_PIJE <- filter(laguna_pre, species == "PIJE") # create data frame w/ only PIJE sp.
laguna_pre_QUKE <- filter(laguna_pre, species == "QUKE") # create data frame w/ only QUKE sp.

#### PIJE

laguna_pre_PIJE_plots <- unique(laguna_pre_PIJE$plot_id) # print each plot ID where PIJE is present

# create a data frame for each plot 
## NOTE: each plot is an 11.3m radius circular plot
laguna_pre_PIJE_128 <- filter(laguna_pre_PIJE, plot_id == "128")
laguna_pre_PIJE_129 <- filter(laguna_pre_PIJE, plot_id == "129")
laguna_pre_PIJE_130 <- filter(laguna_pre_PIJE, plot_id == "130")
laguna_pre_PIJE_131 <- filter(laguna_pre_PIJE, plot_id == "131")
laguna_pre_PIJE_132 <- filter(laguna_pre_PIJE, plot_id == "132")
laguna_pre_PIJE_133 <- filter(laguna_pre_PIJE, plot_id == "133")
laguna_pre_PIJE_134 <- filter(laguna_pre_PIJE, plot_id == "134")
laguna_pre_PIJE_135 <- filter(laguna_pre_PIJE, plot_id == "135")
laguna_pre_PIJE_137 <- filter(laguna_pre_PIJE, plot_id == "137")
laguna_pre_PIJE_138 <- filter(laguna_pre_PIJE, plot_id == "138")
laguna_pre_PIJE_139 <- filter(laguna_pre_PIJE, plot_id == "139")
laguna_pre_PIJE_140 <- filter(laguna_pre_PIJE, plot_id == "140")
laguna_pre_PIJE_141 <- filter(laguna_pre_PIJE, plot_id == "141")
laguna_pre_PIJE_142 <- filter(laguna_pre_PIJE, plot_id == "142")
laguna_pre_PIJE_143 <- filter(laguna_pre_PIJE, plot_id == "143")
laguna_pre_PIJE_144 <- filter(laguna_pre_PIJE, plot_id == "144")
laguna_pre_PIJE_170 <- filter(laguna_pre_PIJE, plot_id == "170")
laguna_pre_PIJE_171 <- filter(laguna_pre_PIJE, plot_id == "171")
laguna_pre_PIJE_172 <- filter(laguna_pre_PIJE, plot_id == "172")
laguna_pre_PIJE_173 <- filter(laguna_pre_PIJE, plot_id == "173")
laguna_pre_PIJE_175 <- filter(laguna_pre_PIJE, plot_id == "175")
laguna_pre_PIJE_176 <- filter(laguna_pre_PIJE, plot_id == "176")
laguna_pre_PIJE_177 <- filter(laguna_pre_PIJE, plot_id == "177")
laguna_pre_PIJE_179 <- filter(laguna_pre_PIJE, plot_id == "179")
laguna_pre_PIJE_180 <- filter(laguna_pre_PIJE, plot_id == "180")
laguna_pre_PIJE_181 <- filter(laguna_pre_PIJE, plot_id == "181")
laguna_pre_PIJE_195 <- filter(laguna_pre_PIJE, plot_id == "195")
laguna_pre_PIJE_197 <- filter(laguna_pre_PIJE, plot_id == "197")
laguna_pre_PIJE_198 <- filter(laguna_pre_PIJE, plot_id == "198")
laguna_pre_PIJE_199 <- filter(laguna_pre_PIJE, plot_id == "199")
laguna_pre_PIJE_200 <- filter(laguna_pre_PIJE, plot_id == "200")

# calculate plot area
plot_area <- pi*(11.3^2)
## plot area = 401.15m^2

# create vectors of the sum of each species' area per plot
l_p_128 <- sum(laguna_pre_PIJE_128$tree_area)
l_p_129 <- sum(laguna_pre_PIJE_129$tree_area)
l_p_130 <- sum(laguna_pre_PIJE_130$tree_area)
l_p_131 <- sum(laguna_pre_PIJE_131$tree_area)
l_p_132 <- sum(laguna_pre_PIJE_132$tree_area)
l_p_133 <- sum(laguna_pre_PIJE_133$tree_area)
l_p_134 <- sum(laguna_pre_PIJE_134$tree_area)
l_p_135 <- sum(laguna_pre_PIJE_135$tree_area)
l_p_137 <- sum(laguna_pre_PIJE_137$tree_area)
l_p_138 <- sum(laguna_pre_PIJE_138$tree_area)
l_p_139 <- sum(laguna_pre_PIJE_139$tree_area)
l_p_140 <- sum(laguna_pre_PIJE_140$tree_area)
l_p_141 <- sum(laguna_pre_PIJE_141$tree_area)
l_p_142 <- sum(laguna_pre_PIJE_142$tree_area)
l_p_143 <- sum(laguna_pre_PIJE_143$tree_area)
l_p_144 <- sum(laguna_pre_PIJE_144$tree_area)
l_p_170 <- sum(laguna_pre_PIJE_170$tree_area)
l_p_171 <- sum(laguna_pre_PIJE_171$tree_area)
l_p_172 <- sum(laguna_pre_PIJE_172$tree_area)
l_p_173 <- sum(laguna_pre_PIJE_173$tree_area)
l_p_175 <- sum(laguna_pre_PIJE_175$tree_area)
l_p_176 <- sum(laguna_pre_PIJE_176$tree_area)
l_p_177 <- sum(laguna_pre_PIJE_177$tree_area)
l_p_179 <- sum(laguna_pre_PIJE_179$tree_area)
l_p_180 <- sum(laguna_pre_PIJE_180$tree_area)
l_p_181 <- sum(laguna_pre_PIJE_181$tree_area)
l_p_195 <- sum(laguna_pre_PIJE_195$tree_area)
l_p_197 <- sum(laguna_pre_PIJE_197$tree_area)
l_p_198 <- sum(laguna_pre_PIJE_198$tree_area)
l_p_199 <- sum(laguna_pre_PIJE_199$tree_area)
l_p_200 <- sum(laguna_pre_PIJE_200$tree_area)

# create vectors of average height of each species per plot
h_128 <- mean(laguna_pre_PIJE_128$ht)
h_129 <- mean(laguna_pre_PIJE_129$ht)
h_130 <- mean(laguna_pre_PIJE_130$ht)
h_131 <- mean(laguna_pre_PIJE_131$ht)
h_132 <- mean(laguna_pre_PIJE_132$ht)
h_133 <- mean(laguna_pre_PIJE_133$ht)
h_134 <- mean(laguna_pre_PIJE_134$ht)
h_135 <- mean(laguna_pre_PIJE_135$ht)
h_137 <- mean(laguna_pre_PIJE_137$ht)
h_138 <- mean(laguna_pre_PIJE_138$ht)
h_139 <- mean(laguna_pre_PIJE_139$ht)
h_140 <- mean(laguna_pre_PIJE_140$ht)
h_141 <- mean(laguna_pre_PIJE_141$ht)
h_142 <- mean(laguna_pre_PIJE_142$ht)
h_143 <- mean(laguna_pre_PIJE_143$ht)
h_144 <- mean(laguna_pre_PIJE_144$ht)
h_170 <- mean(laguna_pre_PIJE_170$ht)
h_171 <- mean(laguna_pre_PIJE_171$ht)
h_172 <- mean(laguna_pre_PIJE_172$ht)
h_173 <- mean(laguna_pre_PIJE_173$ht)
h_175 <- mean(laguna_pre_PIJE_175$ht)
h_176 <- mean(laguna_pre_PIJE_176$ht)
h_177 <- mean(laguna_pre_PIJE_177$ht)
h_179 <- mean(laguna_pre_PIJE_179$ht)
h_180 <- mean(laguna_pre_PIJE_180$ht)
h_181 <- mean(laguna_pre_PIJE_181$ht)
h_195 <- mean(laguna_pre_PIJE_195$ht)
h_197 <- mean(laguna_pre_PIJE_197$ht)
h_198 <- mean(laguna_pre_PIJE_198$ht)
h_199 <- mean(laguna_pre_PIJE_199$ht)
h_200 <- mean(laguna_pre_PIJE_200$ht)

unique(laguna_pre_PIJE_clean$plot_id) # view plots with PIJE in laguna mtn.

# create data frame: project, year, plot_id, & abundance for PIJE
laguna_pre_PIJE_clean <- data.frame(
  project = rep("Laguna Mtn.", times = length(laguna_pre_PIJE_plots)), 
  species = rep("PIJE", times = length(laguna_pre_PIJE_plots)),
  plot_id = c(laguna_pre_PIJE_plots),
  abundance = c(l_p_128/plot_area, l_p_129/plot_area, l_p_130/plot_area, l_p_131/plot_area, l_p_132/plot_area, l_p_133/plot_area, l_p_134/plot_area, l_p_135/plot_area, l_p_137/plot_area, l_p_138/plot_area, l_p_139/plot_area, l_p_140/plot_area, l_p_141/plot_area, l_p_142/plot_area, l_p_143/plot_area, l_p_144/plot_area, l_p_170/plot_area, l_p_171/plot_area, l_p_172/plot_area, l_p_173/plot_area, l_p_175/plot_area, l_p_176/plot_area, l_p_177/plot_area, l_p_179/plot_area, l_p_180/plot_area, l_p_181/plot_area, l_p_195/plot_area, l_p_197/plot_area, l_p_198/plot_area, l_p_199/plot_area, l_p_200/plot_area),
  avg_ht = c(h_128, h_129, h_130, h_131, h_132, h_133, h_134, h_135, h_137, h_138, h_139, h_140, h_141, h_142, h_143, h_144, h_170, h_171, h_172, h_173, h_175, h_176, h_177, h_179, h_180, h_181, h_195, h_197, h_198, h_199, h_200),
  easting = c(552604, 552907, 552703, 552825, 552934, 552930, 552944, 553054, 552809, 552825, 552701, 552968, 552953, 552964, 552871, 552990, 553555, 553650, 553694, 553741, 553748, 553722, 553810, 553733, 553796, 553745, 553844, 553803, 553697, 553634, 553638),
  northing = c(3635674, 3635674, 3635674, 3635674, 3635625, 3635689, 3635441, 3635389, 3635340, 3635401, 3635401, 3635072, 3634891, 3636126, 3635065, 3635000, 3635917, 3635822, 3636045, 3636012, 3635916, 3635733, 3635775, 3635619, 3635629, 3635589, 3635701, 3635729, 3635950, 3635975, 3635910)
)

#### QUKE

laguna_pre_QUKE_plots <- unique(laguna_pre_QUKE$plot_id) # print each plot ID where QUKE is present

# create a data frame for each plot 
## NOTE: each plot is an 11.3m radius circular plot
laguna_pre_QUKE_128 <- filter(laguna_pre_QUKE, plot_id == "128")
laguna_pre_QUKE_129 <- filter(laguna_pre_QUKE, plot_id == "129")
laguna_pre_QUKE_130 <- filter(laguna_pre_QUKE, plot_id == "130")
laguna_pre_QUKE_131 <- filter(laguna_pre_QUKE, plot_id == "131")
laguna_pre_QUKE_133 <- filter(laguna_pre_QUKE, plot_id == "133")
laguna_pre_QUKE_134 <- filter(laguna_pre_QUKE, plot_id == "134")
laguna_pre_QUKE_135 <- filter(laguna_pre_QUKE, plot_id == "135")
laguna_pre_QUKE_137 <- filter(laguna_pre_QUKE, plot_id == "137")
laguna_pre_QUKE_138 <- filter(laguna_pre_QUKE, plot_id == "138")
laguna_pre_QUKE_139 <- filter(laguna_pre_QUKE, plot_id == "139")
laguna_pre_QUKE_140 <- filter(laguna_pre_QUKE, plot_id == "140")
laguna_pre_QUKE_141 <- filter(laguna_pre_QUKE, plot_id == "141")
laguna_pre_QUKE_142 <- filter(laguna_pre_QUKE, plot_id == "142")
laguna_pre_QUKE_143 <- filter(laguna_pre_QUKE, plot_id == "143")
laguna_pre_QUKE_144 <- filter(laguna_pre_QUKE, plot_id == "144")
laguna_pre_QUKE_170 <- filter(laguna_pre_QUKE, plot_id == "170")
laguna_pre_QUKE_171 <- filter(laguna_pre_QUKE, plot_id == "171")
laguna_pre_QUKE_172 <- filter(laguna_pre_QUKE, plot_id == "172")
laguna_pre_QUKE_173 <- filter(laguna_pre_QUKE, plot_id == "173")
laguna_pre_QUKE_175 <- filter(laguna_pre_QUKE, plot_id == "175")
laguna_pre_QUKE_176 <- filter(laguna_pre_QUKE, plot_id == "176")
laguna_pre_QUKE_177 <- filter(laguna_pre_QUKE, plot_id == "177")
laguna_pre_QUKE_179 <- filter(laguna_pre_QUKE, plot_id == "179")
laguna_pre_QUKE_180 <- filter(laguna_pre_QUKE, plot_id == "180")
laguna_pre_QUKE_181 <- filter(laguna_pre_QUKE, plot_id == "181")
laguna_pre_QUKE_195 <- filter(laguna_pre_QUKE, plot_id == "195")
laguna_pre_QUKE_197 <- filter(laguna_pre_QUKE, plot_id == "197")
laguna_pre_QUKE_198 <- filter(laguna_pre_QUKE, plot_id == "198")
laguna_pre_QUKE_199 <- filter(laguna_pre_QUKE, plot_id == "199")
laguna_pre_QUKE_200 <- filter(laguna_pre_QUKE, plot_id == "200")

# calculate plot area
plot_area <- pi*(11.3^2)
## plot area = 401.15m^2

# create vectors of the sum of each species' area per plot
l_q_128 <- sum(laguna_pre_QUKE_128$tree_area)
l_q_129 <- sum(laguna_pre_QUKE_129$tree_area)
l_q_130 <- sum(laguna_pre_QUKE_130$tree_area)
l_q_131 <- sum(laguna_pre_QUKE_131$tree_area)
l_q_133 <- sum(laguna_pre_QUKE_133$tree_area)
l_q_134 <- sum(laguna_pre_QUKE_134$tree_area)
l_q_135 <- sum(laguna_pre_QUKE_135$tree_area)
l_q_137 <- sum(laguna_pre_QUKE_137$tree_area)
l_q_138 <- sum(laguna_pre_QUKE_138$tree_area)
l_q_139 <- sum(laguna_pre_QUKE_139$tree_area)
l_q_140 <- sum(laguna_pre_QUKE_140$tree_area)
l_q_141 <- sum(laguna_pre_QUKE_141$tree_area)
l_q_142 <- sum(laguna_pre_QUKE_142$tree_area)
l_q_143 <- sum(laguna_pre_QUKE_143$tree_area)
l_q_144 <- sum(laguna_pre_QUKE_144$tree_area)
l_q_170 <- sum(laguna_pre_QUKE_170$tree_area)
l_q_171 <- sum(laguna_pre_QUKE_171$tree_area)
l_q_172 <- sum(laguna_pre_QUKE_172$tree_area)
l_q_173 <- sum(laguna_pre_QUKE_173$tree_area)
l_q_175 <- sum(laguna_pre_QUKE_175$tree_area)
l_q_176 <- sum(laguna_pre_QUKE_176$tree_area)
l_q_177 <- sum(laguna_pre_QUKE_177$tree_area)
l_q_179 <- sum(laguna_pre_QUKE_179$tree_area)
l_q_180 <- sum(laguna_pre_QUKE_180$tree_area)
l_q_181 <- sum(laguna_pre_QUKE_181$tree_area)
l_q_195 <- sum(laguna_pre_QUKE_195$tree_area)
l_q_197 <- sum(laguna_pre_QUKE_197$tree_area)
l_q_198 <- sum(laguna_pre_QUKE_198$tree_area)
l_q_199 <- sum(laguna_pre_QUKE_199$tree_area)
l_q_200 <- sum(laguna_pre_QUKE_200$tree_area)

# create vectors of the average height of each species per plot
h_q_128 <- mean(laguna_pre_QUKE_128$ht)
h_q_129 <- mean(laguna_pre_QUKE_129$ht)
h_q_130 <- mean(laguna_pre_QUKE_130$ht)
h_q_131 <- mean(laguna_pre_QUKE_131$ht)
h_q_133 <- mean(laguna_pre_QUKE_133$ht)
h_q_134 <- mean(laguna_pre_QUKE_134$ht)
h_q_135 <- mean(laguna_pre_QUKE_135$ht)
h_q_137 <- mean(laguna_pre_QUKE_137$ht)
h_q_138 <- mean(laguna_pre_QUKE_138$ht)
h_q_139 <- mean(laguna_pre_QUKE_139$ht)
h_q_140 <- mean(laguna_pre_QUKE_140$ht)
h_q_141 <- mean(laguna_pre_QUKE_141$ht)
h_q_142 <- mean(laguna_pre_QUKE_142$ht)
h_q_143 <- mean(laguna_pre_QUKE_143$ht)
h_q_144 <- mean(laguna_pre_QUKE_144$ht)
h_q_170 <- mean(laguna_pre_QUKE_170$ht)
h_q_171 <- mean(laguna_pre_QUKE_171$ht)
h_q_172 <- mean(laguna_pre_QUKE_172$ht)
h_q_173 <- mean(laguna_pre_QUKE_173$ht)
h_q_175 <- mean(laguna_pre_QUKE_175$ht)
h_q_176 <- mean(laguna_pre_QUKE_176$ht)
h_q_177 <- mean(laguna_pre_QUKE_177$ht)
h_q_179 <- mean(laguna_pre_QUKE_179$ht)
h_q_180 <- mean(laguna_pre_QUKE_180$ht)
h_q_181 <- mean(laguna_pre_QUKE_181$ht)
h_q_195 <- mean(laguna_pre_QUKE_195$ht)
h_q_197 <- mean(laguna_pre_QUKE_197$ht)
h_q_198 <- mean(laguna_pre_QUKE_198$ht)
h_q_199 <- mean(laguna_pre_QUKE_199$ht)
h_q_200 <- mean(laguna_pre_QUKE_200$ht)

unique(laguna_pre_QUKE_clean$plot_id)

# create data frame: project, year, plot_id, & abundance for QUKE
laguna_pre_QUKE_clean <- data.frame(
  project = rep("Laguna Mtn.", times = length(laguna_pre_QUKE_plots)), 
  species = rep("QUKE", times = length(laguna_pre_QUKE_plots)),
  plot_id = c(laguna_pre_QUKE_plots),
  abundance = c(l_q_128/plot_area, l_q_129/plot_area, l_q_130/plot_area, l_q_131/plot_area, l_q_133/plot_area, l_q_134/plot_area, l_q_135/plot_area, l_q_137/plot_area, l_q_138/plot_area, l_q_139/plot_area, l_q_140/plot_area, l_q_141/plot_area, l_q_142/plot_area, l_q_143/plot_area, l_q_144/plot_area, l_q_170/plot_area, l_q_171/plot_area, l_q_172/plot_area, l_q_173/plot_area, l_q_175/plot_area, l_q_176/plot_area, l_q_177/plot_area, l_q_179/plot_area, l_q_180/plot_area, l_q_181/plot_area, l_q_195/plot_area, l_q_197/plot_area, l_q_198/plot_area, l_q_199/plot_area, l_q_200/plot_area),
  avg_ht = c(h_q_128, h_q_129, h_q_130, h_q_131, h_q_133, h_q_134, h_q_135, h_q_137, h_q_138, h_q_139, h_q_140, h_q_141, h_q_142, h_q_143, h_q_144, h_q_170, h_q_171, h_q_172, h_q_173, h_q_175, h_q_176, h_q_177, h_q_179, h_q_180, h_q_181, h_q_195, h_q_197, h_q_198, h_q_199, h_q_200),
  easting = c(552604, 552907, 552703, 552825, 552930, 552944, 553054, 552809, 552825, 552701, 552953, 552964, 552871, 552990, 553555, 553650, 553694, 553741, 553748, 553722, 553810, 553733, 553796, 553745, 553844, 553738, 553803, 553697, 553634, 553638),
  northing = c(3635674, 3635518, 3635561, 3635690, 3635689, 3635441, 3635389, 3635340, 3635401, 3635401, 3634891, 3636126, 3635065, 3635000, 3635917, 3635822, 3636045, 3636012, 3635916, 3635733, 3635775, 3635619, 3635629, 3635589, 3635701, 3635675, 3635729, 3635950, 3635975, 3635910)
)

l_abundance <- rbind(laguna_pre_PIJE_clean, laguna_pre_QUKE_clean)

# repeat for bluff mesa
unique(bluffmesa_pre$species) # identify species present in bluff mesa fire data

bluffmesa_pre_ABCO <- filter(bluffmesa_pre, species == "ABCO") # create data frame w/ only ABCO sp.
bluffmesa_pre_PIJE <- filter(bluffmesa_pre, species == "PIJE") # create data frame w/ only PIJE sp.

#### ABCO

unique(bluffmesa_pre_ABCO$plot_id) # print each plot ID where ABCO is present

# create a data frame for each plot 
## NOTE: each plot is an 11.3m radius circular plot
bluffmesa_pre_ABCO_24 <- filter(bluffmesa_pre_ABCO, plot_id == "24")
bluffmesa_pre_ABCO_26 <- filter(bluffmesa_pre_ABCO, plot_id == "26")
bluffmesa_pre_ABCO_33 <- filter(bluffmesa_pre_ABCO, plot_id == "33")
bluffmesa_pre_ABCO_48 <- filter(bluffmesa_pre_ABCO, plot_id == "48")
bluffmesa_pre_ABCO_49 <- filter(bluffmesa_pre_ABCO, plot_id == "49")
bluffmesa_pre_ABCO_52 <- filter(bluffmesa_pre_ABCO, plot_id == "52")

# calculate plot area
plot_area <- pi*(11.3^2)
## plot area = 401.15m^2

# create data frame: project, year, plot_id, & abundance for ABCO
bluffmesa_pre_ABCO_clean <- data.frame(
  project = rep("Bluff Mesa", times = length(unique(bluffmesa_pre_ABCO$plot_id))), 
  species = rep("ABCO", times = length(unique(bluffmesa_pre_ABCO$plot_id))),
  plot_id = c(unique(bluffmesa_pre_ABCO$plot_id)),
  abundance = c(sum(bluffmesa_pre_ABCO_24$tree_area)/plot_area, sum(bluffmesa_pre_ABCO_26$tree_area)/plot_area, sum(bluffmesa_pre_ABCO_33$tree_area)/plot_area, sum(bluffmesa_pre_ABCO_48$tree_area)/plot_area, sum(bluffmesa_pre_ABCO_49$tree_area)/plot_area, sum(bluffmesa_pre_ABCO_52$tree_area)/plot_area),
  avg_ht = c(mean(bluffmesa_pre_ABCO_24$ht), mean(bluffmesa_pre_ABCO_26$ht), mean(bluffmesa_pre_ABCO_33$ht), mean(bluffmesa_pre_ABCO_48$ht), mean(bluffmesa_pre_ABCO_49$ht), mean(bluffmesa_pre_ABCO_52$ht)),
  easting = c(502045, 502155, 502518, 502663, 502600, 503370),
  northing = c(3786845, 3786746, 3786610, 3787038, 3787201, 3786975)
) # note --> no abundance data for plot 26 because there is no dbh data

#### PIJE

unique(bluffmesa_pre_PIJE$plot_id) # print each plot ID where PIJE is present

# create a data frame for each plot 
## NOTE: each plot is an 11.3m radius circular plot
bluffmesa_pre_PIJE_24 <- filter(bluffmesa_pre_PIJE, plot_id == "24")
bluffmesa_pre_PIJE_25 <- filter(bluffmesa_pre_PIJE, plot_id == "25")
bluffmesa_pre_PIJE_26 <- filter(bluffmesa_pre_PIJE, plot_id == "26")
bluffmesa_pre_PIJE_27 <- filter(bluffmesa_pre_PIJE, plot_id == "27")
bluffmesa_pre_PIJE_33 <- filter(bluffmesa_pre_PIJE, plot_id == "33")
bluffmesa_pre_PIJE_49 <- filter(bluffmesa_pre_PIJE, plot_id == "49")
bluffmesa_pre_PIJE_50 <- filter(bluffmesa_pre_PIJE, plot_id == "50")
bluffmesa_pre_PIJE_51 <- filter(bluffmesa_pre_PIJE, plot_id == "51")
bluffmesa_pre_PIJE_52 <- filter(bluffmesa_pre_PIJE, plot_id == "52")
bluffmesa_pre_PIJE_53 <- filter(bluffmesa_pre_PIJE, plot_id == "53")

# create data frame: project, year, plot_id, & abundance for PIJE
bluffmesa_pre_PIJE_clean <- data.frame(
  project = rep("Bluff Mesa", times = length(unique(bluffmesa_pre_PIJE$plot_id))), 
  species = rep("PIJE", times = length(unique(bluffmesa_pre_PIJE$plot_id))),
  plot_id = c(unique(bluffmesa_pre_PIJE$plot_id)),
  abundance = c(sum(bluffmesa_pre_PIJE_24$tree_area)/plot_area, sum(bluffmesa_pre_PIJE_25$tree_area)/plot_area, sum(bluffmesa_pre_PIJE_26$tree_area)/plot_area, sum(bluffmesa_pre_PIJE_27$tree_area)/plot_area, sum(bluffmesa_pre_PIJE_33$tree_area)/plot_area, sum(bluffmesa_pre_PIJE_49$tree_area)/plot_area, sum(bluffmesa_pre_PIJE_50$tree_area)/plot_area, sum(bluffmesa_pre_PIJE_51$tree_area)/plot_area, sum(bluffmesa_pre_PIJE_52$tree_area)/plot_area, sum(bluffmesa_pre_PIJE_53$tree_area)/plot_area),
  avg_ht = c(mean(bluffmesa_pre_PIJE_24$ht), mean(bluffmesa_pre_PIJE_25$ht), mean(bluffmesa_pre_PIJE_26$ht), mean(bluffmesa_pre_PIJE_27$ht), mean(bluffmesa_pre_PIJE_33$ht), mean(bluffmesa_pre_PIJE_49$ht), mean(bluffmesa_pre_PIJE_50$ht), mean(bluffmesa_pre_PIJE_51$ht), mean(bluffmesa_pre_PIJE_52$ht), mean(bluffmesa_pre_PIJE_53$ht)),
  easting = c(502045, 502018, 502155, 502360, 502518, 502600, 502811, 503248, 503370, 502980),
  northing = c(3786845, 3786660, 3786746, 3786721, 3786610, 3787201, 3787146, 3787101, 3786975, 3787237)
)

# combine all pre-fire data from bluff mesa plots
bm_abundance <- rbind(bluffmesa_pre_PIJE_clean, bluffmesa_pre_ABCO_clean)

abundance_whole <- rbind(l_abundance, bm_abundance)
# note: BM 26 ABCO = NA b/c no dbh data recorded
```


### post-fire data
#### Nicole's data
```{r}
# load in raw post-fire bluff mesa data (2021)
bm_24_2021_trees <- read.csv("data/Nicole-data/bluffmesadata/BM_24_2021_trees.csv")
bm_25_2021_trees <- read.csv("data/Nicole-data/bluffmesadata/BM_25_2021_trees.csv")
bm_26_2021_trees <- read.csv("data/Nicole-data/bluffmesadata/BM_26_2021_trees.csv")
bm_27_2021_trees <- read.csv("data/Nicole-data/bluffmesadata/BM_27_2021_trees.csv")
bm_33_2021_trees <- read.csv("data/Nicole-data/bluffmesadata/BM_33_2021_trees.csv")
bm_48_2021_trees <- read.csv("data/Nicole-data/bluffmesadata/BM_48_2021_trees.csv")
bm_49_2021_trees <- read.csv("data/Nicole-data/bluffmesadata/BM_49_2021_trees.csv")
bm_50_2021_trees <- read.csv("data/Nicole-data/bluffmesadata/BM_50_2021_trees.csv")
bm_51_2021_trees <- read.csv("data/Nicole-data/bluffmesadata/BM_51_2021_trees.csv")
bm_52_2021_trees <- read.csv("data/Nicole-data/bluffmesadata/BM_52_2021_trees.csv")
bm_53_2021_trees <- read.csv("data/Nicole-data/bluffmesadata/BM_53_2021_trees.csv")

# combine raw pre-fire bluff mesa data into one data frame
bluffmesa_post <- rbind(
  bm_24_2021_trees, bm_25_2021_trees, bm_26_2021_trees, bm_27_2021_trees, bm_33_2021_trees, bm_48_2021_trees, bm_49_2021_trees, bm_50_2021_trees, bm_51_2021_trees, bm_52_2021_trees, bm_53_2021_trees) %>%
  clean_names() %>%
  select(tag_no, status, dbh, ht, crwn_rto, crwn_rad, char_ht, scorch_ht, cr_sc_pct, uv1, uv2, uv3, species)

```

### leaf trait data
#### leaf area
```{r}
# determine the species present in the pre/post fire data
laguna_species <- unique(laguna_pre$species) # create list of all species present in laguna fire data
bluffmesa_species <- unique(bluffmesa_pre$species) # create list of all species present in bluff mesa fire data
 
# read in data from TRY database
leaf_area <- read.csv("data/Veg-data/leaf_area.csv") %>%
  clean_names() %>%
  select(dataset_id, dataset, species_name, trait_id, trait_name, data_name, orig_value_str, orig_unit_str, std_value) %>%
  slice_head(n = 65)

# calculate community weighted mean (trait value x species abundance)
## laguna mountain
laguna_plots <- unique(laguna_pre$plot_id) %>% # list all of the plots included in the laguna mountain burn area
  as.character()
leaf_area_QUCH <- leaf_area %>% # subset leaf area data to only include QUCH
  filter(leaf_area$species_name == "Quercus chapmanii")
leaf_area_QUKE <- leaf_area %>% # subset leaf area data to only include QUKE
  filter(leaf_area$species_name == "Quercus keloggii")
leaf_area_ABCO <- leaf_area %>% # subset leaf area data to only include ABCO
  filter(leaf_area$species_name == "Abies concolor")

## bluff mesa
bluffmesa_plots <- unique(bluffmesa_pre$plot_id) %>% # list all of the plots included in the bluff mesa burn area
  as.character()
```


##### building bar plots
```{r}
### leaf area
## laguna mountain
# calculate QUCH mean leaf area
QUCH_leaf_area <- (15.76 + 14.76 + 28.2 + 18.57 + 14.29 + 21.47 + 24.14 + 17 + 9.53 + 15.16 + 12.17 + 14.22 + 12.45 + 21.74 + 20.46 + 18.23 +12.71 + 29.86 + 22.27 + 17.11 + 15.23 + 11.67 + 17.02 + 16.09 + 12.36 + 12.5 + 20.97 + 18.67 + 21.87 + 18.84 + 18.44 + 14.72 + 14.64 + 17.83 + 11.87 + 21.58 + 12.54 + 15.76 + 15.76 + 21.3747)/40 # cm^2

QUKE_leaf_area <- 40.89 # cm&2

laguna_80 <-  (QUCH_leaf_area*0.02188190)+(QUKE_leaf_area*0.127896664) # NOTE: doesn't account for PIJE species present in plot 80; no leaf area data for PIJE
laguna_81 <- (QUCH_leaf_area*0.137503524)+(QUKE_leaf_area*0.132905083) # NOTE: missing PIJE data
laguna_82 <- (QUCH_leaf_area*0.036714895)+(QUKE_leaf_area*0.204246613) # NOTE: missing PIJE data
laguna_83 <- (QUCH_leaf_area*0.030720348)+(QUKE_leaf_area*0.282228933) # NOTE: missing PIJE data
laguna_85 <- (QUKE_leaf_area*0.104909155) # NOTE: missing PIJE data
laguna_86 <- (QUKE_leaf_area*0.084400697) # NOTE: missing PIJE data
laguna_87 <- (QUCH_leaf_area*0.013481479)+(QUKE_leaf_area*0.060271165) # NOTE: missing PIJE data
laguna_88 <- (QUKE_leaf_area*0.210908254) # NOTE: missing PIJE data
laguna_89 <- "NA" # NOTE: missing PIJE and PICO data
laguna_90 <- "NA" # NOTE: nissing PIJE and PICO data
laguna_91 <- (QUKE_leaf_area*0.043702522) # NOTE: missing PIJE and PICO data
laguna_92 <- (QUKE_leaf_area*0.049942439) # NOTE: missing PIJE data
laguna_93 <- (QUKE_leaf_area*0.077707730) # NOTE: missing PIJE data
laguna_95 <- (QUKE_leaf_area*0.203380257) 
laguna_97 <- (QUKE_leaf_area*0.052624520) # NOTE: missing PIJE data
laguna_98 <- (QUKE_leaf_area*0.282672096) # NOTE: missing PIJE data
laguna_99 <- (QUKE_leaf_area*0.005792153) # NOTE: missing PIJE data
laguna_105 <- (QUKE_leaf_area*0.032854765) # NOTE: missing PIJE data
laguna_106 <- "NA" # NOTE: missing PIJE data
laguna_107 <- "NA" # NOTE: missing PIJE data
laguna_108 <- (QUKE_leaf_area*0.066777547) # NOTE: missing PIJE data
laguna_109 <- (QUKE_leaf_area*0.163879317) # NOTE: missing PIJE data
laguna_110 <- (QUCH_leaf_area*0.018574086) # NOTE: missing PIJE data
laguna_111 <- (QUKE_leaf_area*0.111012804) # NOTE: missing PIJE & PICO data
laguna_112 <- (QUKE_leaf_area*0.346895411) # NOTE: missing PIJE & PICO data
laguna_113 <- (QUKE_leaf_area*0.228543739) # NOTE: missing PIJE & PICO data
laguna_114 <- (QUKE_leaf_area*0.098418239) 
laguna_115 <- (QUKE_leaf_area*0.168117903)

# community weighted mean vector
cwm_la_laguna <- c(laguna_80, laguna_81, laguna_82, laguna_83, laguna_85, laguna_86, laguna_87, laguna_88, laguna_89, laguna_90, laguna_91, laguna_92, laguna_93, laguna_95, laguna_97, laguna_98, laguna_99, laguna_105, laguna_106, laguna_107, laguna_108, laguna_109, laguna_110, laguna_111, laguna_112, laguna_113, laguna_114, laguna_115) %>%
  as.numeric()

# data frame w/ plot ID & community weighted mean
laguna_leaf_area <- data.frame(laguna_plots, cwm_la_laguna)

# bar plot of plot x community weighted means
laguna_la_box <-ggplot(laguna_leaf_area, aes(laguna_plots, cwm_la_laguna)) + 
  geom_col(fill = "darkseagreen") +
  xlab("Plot number") +
  ylab("Community weighted mean (cm^2)") +
  theme_bw() 

# laguna_leaf_area %>% mutate(laguna_plots = fct_relevel(laguna_plots, "80", "81", "82", "83", "85", "86", "87", "88", "89", "90", "91", "92", "93", "95", "97", "98", "99", "105", "106", "107", "108", "109", "110", "111", "112", "113", "114", "115")) %>%

laguna_la_box

## bluff mesa
# calculate ABCO mean leaf area
ABCO_leaf_area <- (2.38 + 2.34 + 1.9 + 1.88 + 1.62 + 1.59 + 1.39 + 1.21 + 0.96 + 0.91 + 0.68 + 0.56 + 0.55 + 0.53 + 0.43 + 0.34 + 0.26 + 0.18 + 0.18 + 0.12 + 0.5)/21 # cm^2

bluffmesa_24 <- (ABCO_leaf_area*0.03388088) # NOTE: missing PIJE data
bluffmesa_25 <- "NA" # NOTE: missing PIJE data
bluffmesa_26 <- "NA" # NOTE: missing PIJE and ABCO data
bluffmesa_27 <- "NA" # NOTE: missing PILA data
bluffmesa_33 <- (ABCO_leaf_area*0.12813866) # NOTE: missing PIJE data
bluffmesa_48 <- (ABCO_leaf_area*0.14274096) 
bluffmesa_49 <- (ABCO_leaf_area*0.88398739) # NOTE: missing PIJE data
bluffmesa_50 <- "NA" # NOTE: missing PIJE data
bluffmesa_51 <- "NA" # NOTE: missing PIJE data
bluffmesa_52 <- (ABCO_leaf_area*0.03291174) # NOTE: missing PIJE data
bluffmesa_53 <- "NA" # NOTE: missing PIJE data

# community weighted mean vector
cwm_la_bm <- c(bluffmesa_24, bluffmesa_25, bluffmesa_26, bluffmesa_27, bluffmesa_33, bluffmesa_48, bluffmesa_49, bluffmesa_50, bluffmesa_51, bluffmesa_52, bluffmesa_53) %>%
  as.numeric()

# data frame w/ plot ID & community weighted mean
bluffmesa_leaf_area <- data.frame(bluffmesa_plots, cwm_la_bm)

# bar plot of plot x community weighted means
bluffmesa_la_box <-ggplot(bluffmesa_leaf_area, aes(bluffmesa_plots, cwm_la_bm)) + 
  geom_col(fill = "thistle3") +
  xlab("Plot number") +
  ylab("Community weighted mean (cm^2)") +
  ggtitle("Average leaf area at Bluff Mesa") +
  theme_hc(style = "darkunica") +
  scale_colour_hc("darkunica")

bluffmesa_la_box

```

#### specific leaf area
```{r}
# recall species present in the pre/post fire data
laguna_species 
bluffmesa_species 
 
# read in data from TRY database
specific_leaf_area <- read.csv("data/Veg-data/specific_leaf_area.csv") %>%
  clean_names() %>%
  select(dataset_id, dataset, species_name, trait_id, trait_name, data_name, orig_value_str, orig_unit_str, std_value, unit_name) %>%
  filter(trait_id==c("3115", "3116", "3117")) # only include rows with SLA measurements (exclude rows w/ other data measurements)

unique(specific_leaf_area$species_name) # determine the species included in the SLA data

# calculate community weighted mean (trait value x species abundance)
## laguna mountain
laguna_plots # recall all of the plots included in the laguna mountain burn area

spec_leaf_area_QUCH <- specific_leaf_area %>% # subset leaf area data to only include QUCH
  filter(specific_leaf_area$species_name == "Quercus chapmanii")
spec_leaf_area_QUKE <- specific_leaf_area %>% # subset leaf area data to only include QUKE
  filter(specific_leaf_area$species_name == c("Quercus keloggii", "Quercus kelloggii"))
spec_leaf_area_ABCO <- specific_leaf_area %>% # subset leaf area data to only include ABCO
  filter(specific_leaf_area$species_name == "Abies concolor")
spec_leaf_area_PIJE <- specific_leaf_area %>% # subset leaf area data to only include PIJE
  filter(specific_leaf_area$species_name == "Pinus jeffreyi")
spec_leaf_area_PICO <- specific_leaf_area %>% # subset leaf area data to only include PICO
  filter(specific_leaf_area$species_name == c("Pinus contorta", "Pinus contorta Douglas ex Loudon"))

## bluff mesa
bluffmesa_plots # recall all of the plots included in the bluff mesa burn area

```
##### building bar plots 
```{r}
### specific leaf area
## laguna mountain
# calculate QUCH mean specific leaf area
QUCH_spec_leaf_area <- (86.9100000253 + 76.71517672 + 81.19800333 + 69.21824104 + 102.0117351 + 74.02110998 + 99.60815047 + 90.10005266 + 118.3588317 + 66.34819533 + 98.60234445)/11 # cm^2/g

QUKE_spec_leaf_area <- (111.89) # cm^2/g

ABCO_spec_leaf_area <- (32.681 + 31.959 + 35.768 + 41.892 + 45.124 + 35.422 + 22.062 + 33.712 + 49.623 + 30.11 + 69.36753133 + 66.89536878 + 68.74095514 + 70.46476762 + 71.36563877 + 69.43231441 + 70.55837563 + .28442438 + 61.42034549 + 75.08250825 + 67.5944334 + 72.4450194 + 68.15365551 + 68.03594352 + 77.47747748 + 72.34042553 + 68.78306878 + 84.11214953 + 72.28915663 + 75 + 35.768 + 41.892 + 45.124 + 35.422 + 22.062 + 33.712 + 49.623 + 30.114)/38 # cm^2/g

PIJE_spec_leaf_area <- (30.000000003 + 30.2099999995 + 30)/3 # cm^2/g

PICO_spec_leaf_area <- (37.6 + 15.1 + 98.59960072 + 6628.693094 + 113.5000514 + 401.099687 + 729.4605253 + 921.2678931 + 162.3686046 + 56.7 + 50 + 69.4 + 48.8 + 38.97116134)/14  ### SOME OF THESE MEASUREMENTS FEEL WEIRD

laguna_80b <-  (PIJE_spec_leaf_area*0.237868275)+(QUCH_spec_leaf_area*0.02188190)+(QUKE_spec_leaf_area*0.127896664) 
laguna_81b <- (PIJE_spec_leaf_area*0.105031913)+(QUCH_spec_leaf_area*0.137503524)+(QUKE_spec_leaf_area*0.132905083) 
laguna_82b <- (PIJE_spec_leaf_area*0.224752721)+(QUCH_spec_leaf_area*0.036714895)+(QUKE_spec_leaf_area*0.204246613) 
laguna_83b <- (PIJE_spec_leaf_area*0.328016681)+(QUCH_spec_leaf_area*0.030720348)+(QUKE_spec_leaf_area*0.282228933)
laguna_85b <- (PIJE_spec_leaf_area*0.385574242)+(QUKE_spec_leaf_area*0.104909155) 
laguna_86b <- (PIJE_spec_leaf_area*0.311199977)+(QUKE_spec_leaf_area*0.084400697) 
laguna_87b <- (PIJE_spec_leaf_area*0.221507753)+(QUCH_spec_leaf_area*0.013481479)+(QUKE_spec_leaf_area*0.060271165) 
laguna_88b <- (PIJE_spec_leaf_area*0.063661211)+(QUKE_spec_leaf_area*0.210908254) 
laguna_89b <- (PIJE_spec_leaf_area*0.043035477)+(PICO_spec_leaf_area*0.145042486) 
laguna_90b <- (PIJE_spec_leaf_area*0.006773436)+(PICO_spec_leaf_area*0.157932884) 
laguna_91b <- (PIJE_spec_leaf_area*0.005395098)+(QUKE_spec_leaf_area*0.043702522)+(PICO_spec_leaf_area*0.176365612) 
laguna_92b <- (PIJE_spec_leaf_area*0.061276921)+(QUKE_spec_leaf_area*0.049942439) 
laguna_93b <- (PIJE_spec_leaf_area*0.145917065)+(QUKE_spec_leaf_area*0.077707730)
laguna_95b <- (QUKE_spec_leaf_area*0.203380257) 
laguna_97b <- (PIJE_spec_leaf_area*0.110434842)+(QUKE_spec_leaf_area*0.052624520) 
laguna_98b <- (PIJE_spec_leaf_area*0.010762981)+(QUKE_spec_leaf_area*0.282672096) 
laguna_99b <- (PIJE_spec_leaf_area*0.161122053)+(QUKE_spec_leaf_area*0.005792153) 
laguna_105b <- (PIJE_spec_leaf_area*0.244141475)+(QUKE_spec_leaf_area*0.032854765) 
laguna_106b <- (PIJE_spec_leaf_area*0.321107174) 
laguna_107b <- (PIJE_spec_leaf_area*0.566741914) 
laguna_108b <- (PIJE_spec_leaf_area*0.341350145)+(QUKE_spec_leaf_area*0.066777547) 
laguna_109b <- (PIJE_spec_leaf_area*0.329766035)+(QUKE_spec_leaf_area*0.163879317) 
laguna_110b <- (PIJE_spec_leaf_area*0.309436722)+(QUCH_spec_leaf_area*0.018574086) 
laguna_111b <- (PIJE_spec_leaf_area*0.071225233)+(QUKE_spec_leaf_area*0.111012804)+(PICO_spec_leaf_area*0.042333973) 
laguna_112b <- (PIJE_spec_leaf_area*0.093389655)+(QUKE_spec_leaf_area*0.346895411)+(PICO_spec_leaf_area*0.141405944) 
laguna_113b <- (PIJE_spec_leaf_area*0.043363615)+(QUKE_spec_leaf_area*0.228543739)+(PICO_spec_leaf_area*0.048130629) 
laguna_114b <- (QUKE_spec_leaf_area*0.098418239) 
laguna_115b <- (QUKE_spec_leaf_area*0.168117903)

# community weighted mean vector
cwm_sla_laguna <- c(laguna_80b, laguna_81b, laguna_82b, laguna_83b, laguna_85b, laguna_86b, laguna_87b, laguna_88b, laguna_89b, laguna_90b, laguna_91b, laguna_92b, laguna_93b, laguna_95b, laguna_97b, laguna_98b, laguna_99b, laguna_105b, laguna_106b, laguna_107b, laguna_108b, laguna_109b, laguna_110b, laguna_111b, laguna_112b, laguna_113b, laguna_114b, laguna_115b) %>%
  as.numeric()

# data frame w/ plot ID & community weighted mean
laguna_spec_leaf_area <- data.frame(laguna_plots, cwm_sla_laguna)

# bar plot of plot x community weighted means
laguna_sla_box <-ggplot(laguna_spec_leaf_area, aes(laguna_plots, cwm_sla_laguna)) + 
  geom_col(fill = "deepskyblue") +
  xlab("Plot number") +
  ylab("Community weighted mean (cm^2)") +
  theme_bw() 

# laguna_leaf_area %>% mutate(laguna_plots = fct_relevel(laguna_plots, "80", "81", "82", "83", "85", "86", "87", "88", "89", "90", "91", "92", "93", "95", "97", "98", "99", "105", "106", "107", "108", "109", "110", "111", "112", "113", "114", "115")) %>%

laguna_sla_box

## bluff mesa

bluffmesa_24b <- ((ABCO_spec_leaf_area*0.03388088) + (PIJE_spec_leaf_area*0.34393536))/2
bluffmesa_25b <- (PIJE_spec_leaf_area*0.10642680) 
bluffmesa_26b <- (PIJE_spec_leaf_area*0.11028369) # NOTE: missing ABCO data
bluffmesa_27b <- (PIJE_spec_leaf_area*0.34306622) 
bluffmesa_33b <- ((ABCO_leaf_area*0.12813866) + (PIJE_spec_leaf_area*0.30779671))/2 
bluffmesa_48b <- (ABCO_leaf_area*0.14274096) 
bluffmesa_49b <- ((ABCO_leaf_area*0.88398739) + (PIJE_spec_leaf_area*0.11517914))/2
bluffmesa_50b <- (PIJE_spec_leaf_area*0.11687035) 
bluffmesa_51b <- (PIJE_spec_leaf_area*0.13276554) 
bluffmesa_52b <- ((ABCO_leaf_area*0.03291174) +(PIJE_spec_leaf_area*0.01870311))/2
bluffmesa_53b <- (PIJE_spec_leaf_area*0.14539294) 

# community weighted mean vector
cwm_sla_bm <- c(bluffmesa_24b, bluffmesa_25b, bluffmesa_26b, bluffmesa_27b, bluffmesa_33b, bluffmesa_48b, bluffmesa_49b, bluffmesa_50b, bluffmesa_51b, bluffmesa_52b, bluffmesa_53b) %>%
  as.numeric()

# data frame w/ plot ID & community weighted mean
bluffmesa_spec_leaf_area <- data.frame(bluffmesa_plots, cwm_sla_bm)

# bar plot of plot x community weighted means
bluffmesa_sla_box <-ggplot(bluffmesa_spec_leaf_area, aes(bluffmesa_plots, cwm_sla_bm)) + 
  geom_col(fill = "slategray3") +
  xlab("Plot number") +
  ylab("Community weighted mean (cm^2)") +
  ggtitle("Average specific leaf area at Bluff Mesa") + 
  theme_hc(style = "darkunica") +
  scale_colour_hc("darkunica")

bluffmesa_sla_box

```

#### leaf length 
```{r}
# recall species present in the pre/post fire data
laguna_species 
bluffmesa_species 
 
# read in data from TRY database 
leaf_length <- read.csv("data/Veg-data/leaf_length.csv") %>%
  clean_names() %>%
  select(dataset_id, dataset, species_name, trait_id, trait_name, data_name, orig_value_str, orig_unit_str, std_value, unit_name) %>% 
  filter(trait_id==c("144", "940")) # only include rows with leaf length measurements (exclude rows w/ other data measurements)

unique(leaf_length$species_name) # determine the species included in the SLA data

# calculate community weighted mean (trait value x species abundance)
## laguna mountain
laguna_plots # recall all of the plots included in the laguna mountain burn area

leaf_length_QUCH <- leaf_length %>% # subset leaf length data to only include QUCH
  filter(leaf_length$species_name == "Quercus chapmanii")
leaf_length_QUKE <- leaf_length %>% # subset leaf length data to only include QUKE
  filter(leaf_length$species_name == "Quercus kelloggii")
leaf_length_ABCO <- leaf_length %>% # subset leaf length data to only include ABCO
  filter(leaf_length$species_name == "Abies concolor")
leaf_length_PIJE <- leaf_length %>% # subset leaf length data to only include PIJE
  filter(leaf_length$species_name == "Pinus jeffreyi")
leaf_length_PICO <- leaf_length %>% # subset leaf length data to only include PICO
  filter(leaf_length$species_name == "Pinus contorta")
leaf_length_PILA <- leaf_length %>% # subset leaf length data to only include PILA
  filter(leaf_length$species_name == "Pinus lambertiana") 

## bluff mesa
bluffmesa_plots # recall all of the plots included in the bluff mesa burn area

```

##### building bar plots 
```{r}
### leaf length
## laguna mountain
# calculate QUCH mean leaf length
QUCH_leaf_length <- (6.29 + 7.57 + 8.91 + 7)/3 # cm

QUKE_leaf_length <- (6) # cm

ABCO_leaf_length <- (8.609 + 7.066 + 6.023 + 5.222 + 4.367 + 3.283 + 2.837 + 2.568 + 1.711 + 1.378
 + 1.5)/11 # cm

PIJE_leaf_length <- (12 + 25)/2 # cm

PICO_leaf_length <- (7) # cm

PILA_leaf_length <- (10) # cm

laguna_80c <-  (PIJE_leaf_length*0.237868275)+(QUCH_leaf_length*0.02188190)+(QUKE_leaf_length*0.127896664) 
laguna_81c <- (PIJE_leaf_length*0.105031913)+(QUCH_leaf_length*0.137503524)+(QUKE_leaf_length*0.132905083) 
laguna_82c <- (PIJE_leaf_length*0.224752721)+(QUCH_leaf_length*0.036714895)+(QUKE_leaf_length*0.204246613) 
laguna_83c <- (PIJE_leaf_length*0.328016681)+(QUCH_leaf_length*0.030720348)+(QUKE_leaf_length*0.282228933)
laguna_85c <- (PIJE_leaf_length*0.385574242)+(QUKE_leaf_length*0.104909155) 
laguna_86c <- (PIJE_leaf_length*0.311199977)+(QUKE_leaf_length*0.084400697) 
laguna_87c <- (PIJE_leaf_length*0.221507753)+(QUCH_leaf_length*0.013481479)+(QUKE_leaf_length*0.060271165) 
laguna_88c <- (PIJE_leaf_length*0.063661211)+(QUKE_leaf_length*0.210908254) 
laguna_89c <- (PIJE_leaf_length*0.043035477)+(PICO_leaf_length*0.145042486) 
laguna_90c <- (PIJE_leaf_length*0.006773436)+(PICO_leaf_length*0.157932884) 
laguna_91c <- (PIJE_leaf_length*0.005395098)+(QUKE_leaf_length*0.043702522)+(PICO_leaf_length*0.176365612) 
laguna_92c <- (PIJE_leaf_length*0.061276921)+(QUKE_leaf_length*0.049942439) 
laguna_93c <- (PIJE_leaf_length*0.145917065)+(QUKE_leaf_length*0.077707730)
laguna_95c <- (QUKE_leaf_length*0.203380257) 
laguna_97c <- (PIJE_leaf_length*0.110434842)+(QUKE_leaf_length*0.052624520) 
laguna_98c <- (PIJE_leaf_length*0.010762981)+(QUKE_leaf_length*0.282672096) 
laguna_99c <- (PIJE_leaf_length*0.161122053)+(QUKE_leaf_length*0.005792153) 
laguna_105c <- (PIJE_leaf_length*0.244141475)+(QUKE_leaf_length*0.032854765) 
laguna_106c <- (PIJE_leaf_length*0.321107174) 
laguna_107c <- (PIJE_leaf_length*0.566741914) 
laguna_108c <- (PIJE_leaf_length*0.341350145)+(QUKE_leaf_length*0.066777547) 
laguna_109c <- (PIJE_leaf_length*0.329766035)+(QUKE_leaf_length*0.163879317) 
laguna_110c <- (PIJE_leaf_length*0.309436722)+(QUCH_leaf_length*0.018574086) 
laguna_111c <- (PIJE_leaf_length*0.071225233)+(QUKE_leaf_length*0.111012804)+(PICO_leaf_length*0.042333973) 
laguna_112c <- (PIJE_leaf_length*0.093389655)+(QUKE_leaf_length*0.346895411)+(PICO_leaf_length*0.141405944) 
laguna_113c <- (PIJE_leaf_length*0.043363615)+(QUKE_leaf_length*0.228543739)+(PICO_leaf_length*0.048130629) 
laguna_114c <- (QUKE_leaf_length*0.098418239) 
laguna_115c <- (QUKE_leaf_length*0.168117903)

# community weighted mean vector
cwm_ll_laguna <- c(laguna_80c, laguna_81c, laguna_82c, laguna_83c, laguna_85c, laguna_86c, laguna_87c, laguna_88c, laguna_89c, laguna_90c, laguna_91c, laguna_92c, laguna_93c, laguna_95c, laguna_97c, laguna_98c, laguna_99c, laguna_105c, laguna_106c, laguna_107c, laguna_108c, laguna_109c, laguna_110c, laguna_111c, laguna_112c, laguna_113c, laguna_114c, laguna_115c) %>%
  as.numeric()

# data frame w/ plot ID & community weighted mean
laguna_leaf_length <- data.frame(laguna_plots, cwm_ll_laguna)

# bar plot of plot x community weighted means
laguna_ll_box <-ggplot(laguna_leaf_length, aes(laguna_plots, cwm_ll_laguna)) + 
  geom_col(fill = "darkorchid") +
  xlab("Plot number") +
  ylab("Community weighted mean (cm^2)") +
  theme_bw() 

# laguna_leaf_area %>% mutate(laguna_plots = fct_relevel(laguna_plots, "80", "81", "82", "83", "85", "86", "87", "88", "89", "90", "91", "92", "93", "95", "97", "98", "99", "105", "106", "107", "108", "109", "110", "111", "112", "113", "114", "115")) %>%

laguna_ll_box

## bluff mesa

bluffmesa_1c <- (ABCO_leaf_length*0.033882058) 
bluffmesa_2c <- (PIJE_leaf_length*0.013756363)+(ABCO_leaf_length*0.122857311) 
bluffmesa_3c <- (PIJE_leaf_length*0.094853747)+(ABCO_leaf_length*0.065441891) 
bluffmesa_4c <- (PILA_leaf_length*0.200910212)
bluffmesa_5c <- (PIJE_leaf_length*0.331403790)+(ABCO_leaf_length*0.014806367) 
bluffmesa_6c <- (PIJE_leaf_length*0.228945297)+(ABCO_leaf_length*0.124677735) 
bluffmesa_8c <- (PIJE_leaf_length*0.551092685)+(ABCO_leaf_length*0.009390125)
bluffmesa_9c <- (PIJE_leaf_length*0.113851907)+(ABCO_leaf_length*0.416190579) 
bluffmesa_10c <- (PIJE_leaf_length*0.342088261)+(ABCO_leaf_length*0.466818858) 
bluffmesa_11c <- (PIJE_leaf_length*0.102626674)+(ABCO_leaf_length*0.141235414) 
bluffmesa_12c <- (PIJE_leaf_length*0.471040410)+(ABCO_leaf_length*0.063165479) 
bluffmesa_18c <- (PIJE_leaf_length*0.039417535) 
bluffmesa_20c <- (PIJE_leaf_length*0.219124246)+(ABCO_leaf_length*0.041526157) 
bluffmesa_23c <- (PIJE_leaf_length*0.002634505) 
bluffmesa_101c <- (PIJE_leaf_length*0.767171666) 
bluffmesa_102c <- (PIJE_leaf_length*0.009053176)+(ABCO_leaf_length*0.251733299) 
bluffmesa_103c <- (ABCO_leaf_length*0.098238703) 
bluffmesa_104c <- (PIJE_leaf_length*0.218709766)+(ABCO_leaf_length*0.109433785) 
bluffmesa_105c <- (PIJE_leaf_length*0.015300533)+(ABCO_leaf_length*0.003207769) 
bluffmesa_106c <- (PIJE_leaf_length*0.384255815)+(ABCO_leaf_area*0.078472864) 

# community weighted mean vector
cwm_ll_bm <- c(bluffmesa_1c, bluffmesa_2c, bluffmesa_3c, bluffmesa_4c, bluffmesa_5c, bluffmesa_6c, bluffmesa_8c, bluffmesa_9c, bluffmesa_10c, bluffmesa_11c, bluffmesa_12c, bluffmesa_18c, bluffmesa_20c, bluffmesa_23c, bluffmesa_101c, bluffmesa_102c, bluffmesa_103c, bluffmesa_104c, bluffmesa_105c, bluffmesa_106c) %>%
  as.numeric()

# data frame w/ plot ID & community weighted mean
bluffmesa_leaf_length <- data.frame(bluffmesa_plots, cwm_ll_bm)

# bar plot of plot x community weighted means
bluffmesa_ll_box <-ggplot(bluffmesa_leaf_length, aes(bluffmesa_plots, cwm_ll_bm)) + 
  geom_col(fill = "darkorchid") +
  xlab("Plot number") +
  ylab("Community weighted mean (cm^2)") +
  theme_bw() 

bluffmesa_ll_box

```

#### leaf dry matter content
```{r}
# read in data from TRY database 
ldmc <- read.csv("data/Veg-data/ldmc.csv") %>%
  clean_names() %>%
  select(dataset_id, dataset, species_name, trait_id, trait_name, data_name, orig_value_str, orig_unit_str, std_value, unit_name) %>% 
  filter(trait_id==c("47")) # only include rows with leaf length measurements (exclude rows w/ other data measurements)

unique(ldmc$species_name) # determine the species included in the LDMC data

# calculate community weighted mean (trait value x species abundance)
## laguna mountain
laguna_plots # recall all of the plots included in the laguna mountain burn area

ldmc_ABCO <- ldmc %>% # subset leaf length data to only include ABCO
  filter(ldmc$species_name == "Abies concolor")

## bluff mesa
bluffmesa_plots # recall all of the plots included in the bluff mesa burn area

```

## map building
```{r}
# creating a sample data.frame with your lat/lon points
lon <- c(-38.31,-35.5)
lat <- c(40.96, 37.5)
df <- as.data.frame(cbind(lon,lat))

# getting the map
mapzoe <- get_map(location = c(lon = mean(df$lon), lat = mean(df$lat)), zoom = 4,
                      maptype = "satellite", scale = 2)

# plotting the map with some points on it
ggmap(mapzoe) +
  geom_point(data = df, aes(x = lon, y = lat, fill = "red", alpha = 0.8), size = 5, shape = 21) +
  guides(fill=FALSE, alpha=FALSE, size=FALSE)
```


